import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navigation from "@/app/components/Navigation";
import Providers from "@/app/providers/Providers";

const inter = Inter({
  subsets: ['latin'],
  variable: "--font-inter"
});

export const metadata: Metadata = {
  title: "NFT Marketplace",
  description: "Generated by create next app",
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <>
            <Navigation />
            {children}
          </>
        </Providers>
      </body>
    </html>
  );
}
