import type { Metadata } from "next";
import { Inter, Nunito } from "next/font/google";
import "./globals.css";
import Navigation from "@/components/Navigation";
import Providers from "@/providers/Providers";

const inter = Inter({ subsets: ["latin"] });
const nunito = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "NFT Marketplace",
  description: "Generated by create next app",
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} ${nunito.className}`}>
        <Providers>
          <>
            <Navigation />
            {children}
          </>
        </Providers>
      </body>
    </html>
  );
}
